### ISSUE TITLE
crash on Fire TV when download with 1.72 release

### ISSUE THREAD

**Issue by tsynik** [truefedex/tv-bro#66]
It worked fine before, bu with last update Download doen't work anymore:
```
01-17 06:09:25.293  7188  7362 E AndroidRuntime: Process: com.phlox.tvwebbrowser, PID: 7188
01-17 06:09:25.293  7188  7362 E AndroidRuntime: java.lang.RuntimeException: java.lang.Throwable: A WebView method was called on thread 'DefaultDispatcher-worker-2'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {b4c9dc8} called on null, FYI main Looper is Looper (main, tid 1) {b4c9dc8})
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at android.webkit.WebView.checkThread(WebView.java:2360)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at android.webkit.WebView.getSettings(WebView.java:1943)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at com.phlox.tvwebbrowser.activity.main.MainActivity.onDownloadRequested(MainActivity.kt:592)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at com.phlox.tvwebbrowser.activity.main.MainActivity.access$onDownloadRequested(MainActivity.kt:59)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at com.phlox.tvwebbrowser.activity.main.MainActivity$loadState$1$3.invoke(MainActivity.kt:496)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at com.phlox.tvwebbrowser.activity.main.MainActivity$loadState$1$3.invoke(MainActivity.kt:491)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at com.phlox.tvwebbrowser.utils.observable.ParameterizedEventSource.notifyObservers(SimpleObservable.kt:122)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at com.phlox.tvwebbrowser.utils.observable.ParameterizedEventSource.emit(SimpleObservable.kt:116)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at com.phlox.tvwebbrowser.activity.main.MainActivityViewModel$launchLogcatOutputCoroutine$1.invokeSuspend(MainActivityViewModel.kt:145)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: Caused by: java.lang.Throwable: A WebView method was called on thread 'DefaultDispatcher-worker-2'. All WebView methods must be called on the same thread. (Expected Looper Looper (main, tid 1) {b4c9dc8} called on null, FYI main Looper is Looper (main, tid 1) {b4c9dc8})
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	at android.webkit.WebView.checkThread(WebView.java:2350)
01-17 06:09:25.293  7188  7362 E AndroidRuntime: 	... 14 more
01-17 06:09:25.443   727   794 E InputDispatcher: channel 'fd6834d com.phlox.tvwebbrowser/com.phlox.tvwebbrowser.activity.main.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-17 06:09:25.448   727   809 E ConnectivityService: RemoteException caught trying to send a callback msg for NetworkRequest [ LISTEN id=16, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&FOREGROUND] ]
```

**Comment by truefedex** [comment]
Thank you for log. This helps a lot!
